/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.univ;

public class Pegawai {

    private int gajiTetap = 5857500;

    public int getGajiTetap() {
        return gajiTetap;
    }

    /**
     * @param gajiTetap the gajiTetap to set
     */
    public void setGajiTetap(int gajiTetap) {
        this.gajiTetap = gajiTetap;
    }
}
