/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.univ;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;

public class UniversitasTest {
    private DosenPns dosenPns;
    private StaffKontrak staffKontrak;
    private StaffNonPns staffNonPns;
    private StaffPns staffPns;
    private DosenNonPns dosenNonPns;
    private DosenKontrak dosenKontrak;

    @Before
    public void setUp() throws Exception {
        dosenPns = new DosenPns();
        dosenNonPns = new DosenNonPns();
        dosenKontrak = new DosenKontrak();
        staffKontrak = new StaffKontrak();
        staffNonPns = new StaffNonPns();
        staffPns = new StaffPns();
    }
    
    @Test
    public void testDosenPns(){
        assertEquals(dosenPns.getTotalGaji(), 9895500);
    }
    
    @Test
    public void testStaffKontrak(){
        assertEquals(staffKontrak.getTotalGaji(), 7157500);
    }
    
    @Test
    public void testStaffNonPns(){
        assertEquals(staffNonPns.getTotalGaji(), 7607500);
    }
    
    @Test
    public void testDosenNonPns(){
        assertEquals(dosenNonPns.getTotalGaji(), 6907500);
    }
    
    @Test
    public void testDosenKontrak(){
        assertEquals(dosenKontrak.getTotalGaji(), 8250000);
    }
    
    @Test
    public void testStaffPns(){
        assertEquals(staffPns.getTotalGaji(), 9602500);
    }
}
